### ISSUE TITLE
FHIRProxy may fail when continuation token is too large

### ISSUE THREAD

**Issue by mikemassa84** [microsoft/health-architectures#36]
We ran across an issue where the Azure API for FHIR returns a continuation token that is larger than 4kb. The maxQueryStringLength parameter of Azure Functions is set to 4kb, so anything larger than that is truncated.

Does the FHIRProxy handle this scenario?

See related issue: [https://github.com/microsoft/fhir-server/issues/1567](https://github.com/microsoft/fhir-server/issues/1567)

**Comment by corygstevenson** [comment]
@daemel @sordahl-ga - I thought we fixed this issue. Can you confirm?

**Comment by mikemassa84** [comment]
> @daemel @sordahl-ga - I thought we fixed this issue. Can you confirm?

Still an issue:
https://github.com/microsoft/fhir-server/issues/1567#issuecomment-845478523

**Comment by daemel** [comment]
A change was introduced to the FHIR Service to shorten the token.  Please re-test and inform us issues.
